Codecove test to ignore paths

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -71,13 +71,18 @@ jobs:
     - name: Clean previous coverage files
       run: rm -f coverage/coverage.out
 
-
     - name: Run Tests with Coverage
       run: |
-          mkdir -p coverage
-            go test -coverpkg=./... -coverprofile=coverage/coverage.out.tmp -v ./... || (echo "❌ Go tests failed" && exit 1)
-            (head -1 coverage/coverage.out.tmp && tail -n +2 coverage/coverage.out.tmp | grep -v "internals/handlers/course_handler.go") > coverage/coverage.out
-            rm coverage/coverage.out.tmp
+        mkdir -p coverage
+    
+        echo "📋 Listando paquetes..."
+        EXCLUDED="templateGo/internals/handlers|templateGo/cmd|templateGo/config"
+        PACKAGES=$(go list ./... | grep -v "$EXCLUDED")
+    
+        echo "🏃 Ejecutando tests..."
+        go test -coverpkg=./... -coverprofile=coverage/coverage.out -v $PACKAGES || (echo "❌ Go tests failed" && exit 1)
+    
+        echo "✅ Tests ejecutados y coverage generado."
           
     - name: Check coverage file
       run: |
