Add Codecov test configuration to ignore a path

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -77,9 +77,7 @@ jobs:
     - name: Run Tests with Coverage
       run: |
           mkdir -p coverage
-            go test -coverpkg=./... -coverprofile=coverage/coverage.out.tmp -v ./... || (echo "❌ Go tests failed" && exit 1)
-            (head -1 coverage/coverage.out.tmp && tail -n +2 coverage/coverage.out.tmp | grep -v "internals/handlers/course_handler.go") > coverage/coverage.out
-            rm coverage/coverage.out.tmp
+          go test -coverpkg=./... -coverprofile=coverage/coverage.out -v ./... || (echo "❌ Go tests failed" && exit 1)
           
     - name: Check coverage file
       run: |
@@ -102,6 +100,7 @@ jobs:
         fail_ci_if_error: true
         verbose: true
         flags: unittests
+        codecov_yml_path: codecov.yml
 
     - name: Check Coverage Percentage
       run: |
